import { Puzzle } from '@interfaces/puzzle.interface';

const puzzlesEasy: Puzzle[] = [
  {
    id: 1,
    name: 'Гриб',
    classColorText: 'text-yellow-900',
    classBackground: 'bg-yellow-900',
    size: 5,
    sizeClasses: 'w-16 h-16',
    rowHints: [
      [3],
      [5],
      [3],
      [1],
      [1],
    ],
    colHints: [
      [1],
      [3],
      [5],
      [3],
      [1],
    ],
    solution: [
      [false, true,  true,  true,  false],
      [true,  true,  true,  true,  true ],
      [false, true,  true,  true,  false],
      [false, false, true,  false, false],
      [false, false, true,  false, false],
    ],
    srcImg: 'assets/puzzle-easy-1.webp'
  },
  {
    id: 2,
    name: 'Домик',
    classColorText: 'text-blue-900',
    classBackground: 'bg-blue-900',
    size: 5,
    sizeClasses: 'w-16 h-16',
    rowHints: [
      [1],
      [3],
      [5],
      [3],
      [3],
    ],
    colHints: [
      [1],
      [3],
      [5],
      [3],
      [1],
    ],
    solution: [
      [false, false, true,  false, false],
      [false, true,  true,  true,  false],
      [true,  true,  true,  true,  true ],
      [false, true,  true,  true,  false],
      [false, true,  true,  true,  false],
    ],
    srcImg: 'assets/puzzle-easy-2.webp'
  },
  {
    id: 3,
    name: 'Ёлочка',
    classColorText: 'text-green-600',
    classBackground: 'bg-green-600',
    size: 5,
    sizeClasses: 'w-16 h-16',
    rowHints: [
      [1],
      [3],
      [5],
      [3],
      [1],
    ],
    colHints: [
      [1],
      [3],
      [5],
      [3],
      [1],
    ],
    solution: [
      [false, false, true,  false, false],
      [false, true,  true,  true,  false],
      [true,  true,  true,  true,  true ],
      [false, false, true,  false, false],
      [false, false, true,  false, false],
    ],
    srcImg: 'assets/puzzle-easy-3.webp'
  },
  {
    id: 4,
    "name": "Сердце",
    "classColorText": "text-red-600",
    "classBackground": "bg-red-600",
    "size": 10,
    sizeClasses: 'w-10 h-10',
    "rowHints": [
      [2, 2],
      [0, 8],
      [0, 10],
      [0, 10],
      [0, 10],
      [0, 10],
      [0, 8],
      [0, 6],
      [0, 4],
      [0, 2]
    ],
    "colHints": [
      [4],
      [6],
      [8],
      [9],
      [9],
      [9],
      [9],
      [8],
      [6],
      [4]
    ],
    "solution": [
      [false, false, true,  true,  false, false, true,  true,  false, false],
      [false, true,  true,  true,  true, true,  true,  true, true,  false],
      [true, true,  true,  true,  true,  true,  true,  true,  true,  true],
      [true,  true,  true,  true,  true,  true,  true,  true,  true,  true ],
      [true,  true,  true,  true,  true,  true,  true,  true,  true,  true ],
      [true,  true,  true,  true,  true,  true,  true,  true,  true,  true ],
      [false, true,  true,  true,  true,  true,  true,  true,  true,  false],
      [false, false, true,  true,  true,  true,  true,  true,  false, false],
      [false, false, false, true,  true,  true,  true,  false, false, false],
      [false, false, false, false, true,  true,  false, false, false, false]
    ],
    "srcImg": "assets/puzzle-easy-4.webp"
  },
  {
    id: 5,
    name: 'Космический корабль',
    classColorText: 'text-gray-800',
    classBackground: 'bg-gray-800',
    size: 5,
    sizeClasses: 'w-16 h-16',
    rowHints: [
      [0, 1],
      [0, 3],
      [0, 5],
      [1, 1],
      [1, 1],
    ],
    colHints: [
      [3],
      [2],
      [3],
      [2],
      [3],
    ],
    solution: [
      [false, false, true,  false, false],
      [false, true,  true,  true,  false],
      [true,  true,  true,  true,  true ],
      [true,  false, false, false, true ],
      [true,  false, false, false, true ],
    ],
    srcImg: 'assets/puzzle-easy-5.webp'
  },
];

const puzzlesMedium: Puzzle[] = [
  {
    "id": 1,
    "name": "Рыба",
    "classColorText": "text-blue-500",
    "classBackground": "bg-blue-500",
    "size": 15,
    sizeClasses: 'w-8 h-8 p-0 m-0 leading-4',
    "rowHints": [
      [0,0,3],
      [0,3,1],
      [0,3,1],
      [0,5,2],
      [0,6,3],
      [2,6,2],
      [0,4,8],
      [2,2,8],
      [5,5,2],
      [3,5,2],
      [0,7,2],
      [0,5,1],
      [0,4,1],
      [0,0,4],
      [0,0,3]
    ],
    "colHints": [
      [0,0,2],
      [0,0,4],
      [0,2,2],
      [0,0,7],
      [1,3,2],
      [0,3,3],
      [0,0,10],
      [0,0,12],
      [0,0,13],
      [4,6,3],
      [2,4,2],
      [1,2,1],
      [0,0,4],
      [0,0,8],
      [0,4,5],
    ],
    "solution": [
      [false, false, false,  false,  false, false, false,  false,  false, true,  true, true,  false,  false, false],
      [false, false, false,  false,  false, false, false,  false,  true, true,  true, false,  false,  false, true],
      [false, false, false,  false,  false, false, false,  true,  true, true,  false, false,  false,  false, true],
      [false, false, false,  false,  false, true, true,  true,  true, true,  false, false,  false,  true, true],
      [false, false, false,  true,  true, true, true,  true,  true, false,  false, false,  true,  true, true],

      [false, false, true,  true,  false, true, true,  true,  true, true,  true, false,  true,  true, false],
      [false, true, true,  true,  true, false, true,  true,  true, true,  true, true,  true,  true, false],
      [true, true, false,  true,  true, false, true,  true,  true, true,  true, true,  true,  true, false],
      [true, true, true,  true,  true, false, true,  true,  true, true,  true, false,  false,  true, true],
      [false, true, true,  true,  false, true, true,  true,  true, true,  false, false,  false,  true, true],

      [false, false, false,  true,  true, true, true,  true,  true, true,  false, false,  false,  true, true],
      [false, false, false,  false,  true, true, true,  true,  true, false,  false, false,  false,  false, true],
      [false, false, false,  false,  false, false, true,  true,  true, true,  false, false,  false,  false, true],
      [false, false, false,  false,  false, false, false,  true,  true, true,  true, false,  false,  false, false],
      [false, false, false,  false,  false, false, false,  false,  false, true,  true, true,  false,  false, false],
    ],
    "srcImg": "assets/puzzle-middle-1.webp"
  },
  {
    "id": 2,
    "name": "Олень",
    "classColorText": "text-amber-700",
    "classBackground": "bg-amber-700",
    "size": 15,
    sizeClasses: 'w-8 h-8 p-0 m-0 leading-4',
    "rowHints": [
      [0,0,2,2,2,1],
      [2,2,1,1,2,1],
      [0,4,1,1,2,1],
      [0,0,0,0,5,5],
      [0,0,0,0,2,5],
      [0,0,0,0,0,7],
      [0,0,0,1,1,5],
      [0,0,0,0,0,11],
      [0,0,0,0,0,12],
      [0,0,0,0,0,13],
      [0,0,0,0,8,5],
      [0,0,0,1,3,5],
      [0,0,0,0,5,5],
      [0,0,0,0,3,6],
      [0,0,0,0,3,6],
      [0,0,0,0,0,6]
    ],
    "colHints": [
      [0,0,2],
      [0,3,3],
      [2,2,2],
      [0,4,6],
      [0,5,7],
      [0,2,7],
      [3,1,4],
      [0,0,7],
      [0,2,4],
      [2,6,2],
      [0,0,12],
      [0,0,15],
      [0,4,10],
      [0,1,9],
      [0,4,8],
    ],
    "solution": [
      [true, true, false,  true,  true, false, false,  false,  false, false,  false, true,  true,  false, true],
      [true, true, false,  true,  true, false, true,  false,  false, true,  false, true,  true,  false, true],
      [false, true, true,  true,  true, false, true,  false,  false, true,  false, true,  true,  false, true],
      [false, false, true,  true,  true, true, true,  false,  false, false,  true, true,  true,  true, true],
      [false, false, false,  false,  true, true, false, true,  true, true,  true, true,  false, false, false],

      [false, false, false,  false,  false, false, true, true,  true, true,  true, true,  true, false, false],
      [false, false, false,  false,  false, true, false, true,  false, true,  true, true,  true, true, false],
      [false, false, false,  false,  true, true, true, true,  true, true,  true, true,  true, true, true],
      [false, false, false,  true,  true, true, true, true,  true, true,  true, true,  true, true, true],
      [false, false, true,  true,  true, true, true, true,  true, true,  true, true,  true, true, true],

      [false, true, true,  true,  true, true, true, true,  true, false,  true, true,  true, true, true],
      [false, true, false,  true,  true, true, false, false,  false, false,  true, true,  true, true, true],
      [false, true, true,  true,  true, true, false, false,  false, false,  true, true,  true, true, true],
      [false, false, true,  true,  true, false, false, false,  false, true,  true, true,  true, true, true],
      [false, false, false,  false,  false, false, false, false,  false, true,  true, true,  true, true, true],

    ],
    "srcImg": "assets/puzzle-middle-2.webp"
  },
  {
    "id": 3,
    "name": "Утенок",
    "classColorText": "text-yellow-500",
    "classBackground": "bg-yellow-500",
    "size": 15,
    sizeClasses: 'w-8 h-8 p-0 m-0 leading-4',
    "rowHints": [
      [0,0,3],
      [0,0,5],
      [0,4,3],
      [0,0,7],
      [0,0,5],
      [0,0,3],
      [0,0,5],
      [0,1,8],
      [3,3,3],
      [7,3,2],
      [5,4,2],
      [0,8,2],
      [0,0,10],
      [0,2,3],
      [0,0,6],
    ],
    "colHints": [
      [0,0,0,3],
      [0,0,0,4],
      [0,0,0,5],
      [0,0,0,4],
      [0,0,0,5],
      [0,0,0,6],
      [0,3,2,1],
      [0,2,2,5],
      [0,4,2,6],
      [0,8,2,3],
      [8,2,1,1],
      [2,6,2,1],
      [0,0,4,6],
      [0,0,2,4],
      [0,0,0,1],
    ],
    "solution": [
      [false, false, false,  false,  false, false, false,  false,  false, true,  true, true,  false,  false, false],
      [false, false, false,  false,  false, false, false,  false,  true, true,  true, true,  true,  false, false],
      [false, false, false,  false,  false, false, false,  true,  true, true,  true, false,  true,  true, true],
      [false, false, false,  false,  false, false, false,  true,  true, true,  true, true,  true,  true, false],
      [false, false, false,  false,  false, false, false,  false,  true, true,  true, true,  true,  false, false],

      [false, false, false,  false,  false, false, false,  false,  false, true,  true, true,  false,  false, false],
      [false, false, false,  false,  false, false, false,  false,  true, true,  true, true,  true,  false, false],
      [true, false, false,  false,  false, false, true,  true,  true, true,  true, true,  true,  true, false],
      [true, true, true,  false,  false, true, true,  true,  false, false,  false, true,  true,  true, false],
      [true, true, true,  true,  true, true, true,  false,  true, true,  true, false,  true,  true, false],

      [false, true, true,  true,  true, true, false,  true,  true, true,  true, false,  true,  true, false],
      [false, true, true,  true,  true, true, true,  true,  true, false,  false, true,  true,  false, false],
      [false, false, true,  true,  true, true, true,  true,  true, true,  true, true,  false,  false, false],
      [false, false, false,  false,  true, true, false,  true,  true, true,  false, false,  false,  false, false],
      [false, false, false,  false,  false, false, true,  true,  true, true,  true, true,  false,  false, false],
    ],
    "srcImg": "assets/puzzle-middle-3.webp"
  },
];

const puzzlesHard: Puzzle[] = [
  {
    id: 1,
    name: 'Белка',
    classColorText: 'text-amber-500',
    classBackground: 'bg-amber-500',
    size: 20,
    sizeClasses: 'w-5 h-5 p-0 m-0 leading-4',
    textSizeClass: 'text-sm leading-3',
    rowHints: [
      [0, 0, 0, 7],
      [0, 1, 3, 3],
      [0, 1, 2, 2],
      [2, 2, 2, 2],
      [4, 2, 4, 2],
      [6, 2, 4, 2],
      [2, 4, 2, 7],
      [0, 7,5, 4],
      [1, 6, 4, 2],
      [0, 2,7, 4],
      [0,0,11,4],
      [0,0,11,2],
      [0,0,9,3],
      [0,2,7, 2],
      [0,0,12,2],
      [0,0,12,2],
      [0,0,11,2],
      [0,0,0,14],
      [0,0,0,12],
      [0,0,0,10],
    ],
    colHints: [
      [0,0,0,3],
      [0,2,2,3],
      [4,2,5,1],
      [2,2,2,7],
      [0,0,9,6],
      [0,1,10,6],
      [0,0,0,18],
      [0,0,0,15],
      [0,0,0,12],
      [0,0,3, 12],
      [0,0,7, 11],
      [0,3, 3, 9],
      [0,2, 9, 3],
      [0,1, 7, 2],
      [0,1, 10, 3],
      [0,1, 4, 9],
      [0,2, 4, 4],
      [0,0,3, 3],
      [0,0,0,8],
      [0,0,0,5],
    ],
    solution: [
      [false, false,  false,  false,  false, false, false,  false,  false,  false, false, true,  true,  true,  true, true, true,  true,  false,  false],
      [false, false,  false,  false,  false, true, false, false,  false,  false,  true, true, true, false, false, false, true, true, true, false ],
      [false, false, false,  false, false, false, true, false,  false, false, true, true, false,  false, false, false, false, true,  true, false],
      [false, false, false,  false, false, true, true, false,  false, true, true, false, false,  false, true, true, false, false,  true, true],
      [false, false, false,  true, true, true, true, false,  false, true, true, false, false,  true, true, true, true, false,  true, true],
      [false, false, true,  true, true, true, true, true,  false, true, true, false, false,  true, true, true, true, false,  true, true],
      [false, true, true,  false, true, true, true, true,  false, false, true, true, false,  true, true, true, true, true,  true, true],
      [false, true, true,  true, true, true, true, true,  false, false, true, true, true,  true, true, false, true, true,  true, true],
      [true, false, true,  true, true, true, true, true,  true, true, false, true, true,  true, true, false, false, true,  true, false],
      [true, true, false,  false, true, true, true, true,  true, true, true, false, true,  true, true, true, false, false,  false, false],

      [true, true, true,  true, true, true, true, true,  true, true, true, false, true,  true, true, true, false, false,  false, false],
      [false, false, true,  true, true, true, true, true,  true, true, true, true, true,  false, true, true, false, false,  false, false],
      [false, false, false,  false, true, true, true, true,  true, true, true, true, true,  false, true, true, true, false,  false, false],
      [false, false, true,  true, false, false, true, true,  true, true, true, true, true,  false, false, true, true, false,  false, false],
      [false, true, true,  true, true, true, true, true,  true, true, true, true, true,  false, false, true, true, false,  false, false],

      [false, true, true,  true, true, true, true, true,  true, true, true, true, true,  false, false, true, true, false,  false, false],
      [false, true, true,  true, true, true, true, true,  true, true, true, true, false,  false, true, true, false, false,  false, false],
      [false, false, true,  true, true, true, true, true,  true, true, true, true, true,  true, true, true, false, false,  false, false],
      [false, false, false, true,  true, true, true, true, true,  true, true, true, true, true,  true, false, false, false, false,  false],
      [false, false, true, true,  true, true, true, true, true,  true, true, true, false, false,  false, false, false, false, false,  false, false],
    ],
    srcImg: 'assets/puzzle-hard-1.webp'
  },
  {
    "id": 2,
    "name": "Жирафы",
    "classColorText": "text-amber-500",
    "classBackground": "bg-amber-500",
    size: 20,
    sizeClasses: 'w-5 h-5 p-0 m-0 leading-4',
    textSizeClass: 'text-sm leading-3',
    "rowHints": [
      [0,0,0,0,1,1,1,1],
      [0,0,0,0,5,5,1,1],
      [0,0,0,0,0,3,3,5],
      [0,0,0,2,1,1,2,5],
      [0,0,0,0,2,5,2,3],
      [0,0,0,0,2,5,2,1],
      [0,0,0,0,0,2,3,2],
      [0,0,0,0,0,2,1,2],
      [0,0,0,0,0,0,3,3],
      [0,0,0,0,0,0,5,5],
      [0,0,0,0,0,0,6,6],
      [0,0,0,0,0,0,7,7],
      [0,0,0,0,0,0,8,8],
      [0,0,0,0,7,1,7,1],
      [1,3,1,1,1,3,1,1],
      [1,1,1,1,1,1,1,1],
      [1,1,1,1,1,1,1,1],
      [1,1,1,1,1,1,1,1],
      [1,1,1,1,1,1,1,1],
      [0,0,0,0,1,1,1,1],
    ],
    "colHints": [
      [0,0,2],
      [0,0,19],
      [0,0,14],
      [0,2,12],
      [0,1,6],
      [0,2,10],
      [0,4,4],
      [0,4,8],
      [0,4,1],
      [1,2,2],
      [0,0,2],
      [0,0,20],
      [0,0,13],
      [0,2,12],
      [0,0,6],
      [0,2,10],
      [0,4,4],
      [0,4,8],
      [0,4,1],
      [0,2,2],
    ],
    "solution": [
      [true, false, true,  false,  false, false, false,  false,  false, false,  false, true,  false,  true, false,false,false,false,false,false],
      [true, true, true,  true, true, false, false,  false,  false, true, true, true,  true,  true, false,false,true,false,true,false],
      [false, true, true,  true, false, false, false,  false,  false, false, true, true,  true,  false, false,true,true,true,true,true],
      [false, true, true,  false, false, false, true,  false,  true, false, false, true,  true,  false, false,true,true,true,true,true],
      [false, true, true,  false, false, true, true,  true,  true, true, false, true,  true,  false, false,false,true,true,true,false],

      [false, true, true,  false, false, true, true,  true,  true, true, false, true,  true,  false, false,false,false,true,false,false],
      [false, true, true,  false, false, false, true,  true,  true, false, false, true,  true,  false, false,false,false,false,false,false],
      [false, true, true,  false, false, false, false,  true,  false, false, false, true,  true,  false, false,false,false,false,false,false],
      [false, true, true,  true, false, false, false,  false,  false, false, false, true,  true,  true, false,false,false,false,false,false],
      [false, true, true,  true, true, true, false,  false,  false, false, false, true,  true,  true, true,true,false,false,false,false],

      [false, true, true,  true, true, true, true,  false,  false, false, false, true,  true,  true, true,true,true,false,false,false],
      [false, true, true,  true, true, true, true,  true,  false, false, false, true,  true,  true, true,true,true,true,false,false],
      [false, true, true,  true, true, true, true,  true,  true, false, false, true,  true,  true, true,true,true,true,true,false],
      [false, true, true,  true, true, true, true,  true,  false, true, false, true,  true,  true, true,true,true,true,false,true],
      [false, true, false,  true, true, true, false,  true,  false, true, false, true,  false,  true, true,true,false,true,false,true],

      [false, true, false,  true, false, true, false,  true,  false, false, false, true,  false,  true, false,true,false,true,false,false],
      [false, true, false,  true, false, true, false,  true,  false, false, false, true,  false,  true, false,true,false,true,false,false],
      [false, true, false,  true, false, true, false,  true,  false, false, false, true,  false,  true, false,true,false,true,false,false],
      [false, true, false,  true, false, true, false,  true,  false, false, false, true,  false,  true, false,true,false,true,false,false],
      [false, true, false,  true, false, false, false,  false,  false, false, false, true,  false,  true, false,false,false,false,false,false],

    ],
    "srcImg": "assets/puzzle-hard-2.webp"
  },
  {
    "id": 3,
    "name": "Обезьяна",
    "classColorText": "text-amber-900",
    "classBackground": "bg-amber-900",
    size: 20,
    sizeClasses: 'w-5 h-5 p-0 m-0 leading-4',
    textSizeClass: 'text-sm leading-3',
    "rowHints": [
      [0,0,0,0,0,0,0,12],
      [0,0,0,0,0,0,0,14],
      [0,0,0,0,0,0,4,4],
      [0,0,0,0,3,2,2,3],
      [0,0,0,0,4,1,1,4],
      [0,0,2,2,2,2,2,2],
      [1,1,1,2,2,1,1,1],
      [0,1,1,1,1,1,3,1],
      [0,0,0,1,1,2,4,1],
      [0,0,1,5,1,1,5,1],
      [0,0,0,0,1,2,2,1],
      [0,0,0,0,4,1,1,4],
      [0,0,0,0,0,2,4,2],
      [0,0,0,0,3,1,1,3],
      [0,0,0,0,0,2,2,2],
      [0,0,0,0,0,0,4,5],
      [0,0,0,0,0,3,4,5],
      [0,0,0,0,0,0,3,5],
      [0,0,0,0,0,0,3,5],
      [0,0,0,0,0,0,3,6],
    ],
    "colHints": [
      [0,0,0,0,0,5],
      [0,0,0,2,1,2],
      [0,0,1,4,1,3],
      [0,0,0,5,3,4],
      [0,0,0,0,14,3],
      [0,0,0,4,2,6],
      [0,0,3,1,1,3],
      [0,2,1,2,1,1],
      [0,2,1,3,2,1],
      [0,2,1,1,1,1],
      [0,0,2,1,1,1],
      [2,1,2,1,2,1],
      [0,2,1,3,1,1],
      [0,0,3,1,1,3],
      [0,0,4,2,6,1],
      [0,0,0,0,14,5],
      [0,0,0,5,5,5],
      [0,0,1,4,1,4],
      [0,0,0,2,1,4],
      [0,0,0,0,5,3],
    ],
    "solution": [
      [false, false, false,  false,  true, true, true,  true,  true, true,  true, true,  true,  true, true,true,false,false,false,false],
      [false, false, false,  true,  true, true, true,  true,  true, true,  true, true,  true,  true, true,true,true,false,false,false],
      [false, false, false,  true,  true, true, true,  false,  false, false,  false, false,  false,  true, true,true,true,false,false,false],
      [false, false, false,  true,  true, true, false,  true,  true, false,  false, true,  true,  false, true,true,true,false,false,false],
      [false, true, true,  true,  true, false, true,  false,  false, false,  false, false, false,  true, false,true,true,true,true,false],

      [true, true, false,  true,  true, false, false,  true,  true, false,  false, true, true,  false, false,true,true,false,true,true],
      [true, false, true,  false,  true, false, false,  true,  true, false,  false, true, true,  false, false,true,false,true,false,true],
      [true, false, true,  false,  true, false, false,  false,  true, false,  false, false, true,  false, false,true,false,true,false,true],
      [true, false, true,  false,  true, true, false,  false,  false, false,  false, false, false,  false, true,true,true,true,false,true],
      [true, false, true,  true,  true, true, true,  false,  false, true,  false, true, false,  true, true,true,true,true,false,true],

      [false, true, false,  true,  true, false, false,  false,  false, false,  false, false, false,  false, false,true,true,false,true,false],
      [false, false, true,  true,  true, true, false,  true,  false, false,  false, false, true,  false, true,true,true,true,false,false],
      [false, false, false,  false,  true, true, false,  false,  true, true,  true, true, false,  false, true,true,false,false,false,false],
      [false, false, false,  false,  true, true, true,  false,  true, false,  false, true, false,  true, true,true,false,false,false,false],
      [false, false, false,  false,  false, true, true,  false,  false, true,  true, false, false,  true, true,false,false,false,false,false],

      [false, false, false,  false,  true, true, true,  true,  false, false,  false, false, true,  true, true,true,false,false,false,false],
      [false, false, false,  true,  true, true, false,  false,  true, true,  true, true, false,  false, true,true,true,true,true,false],
      [false, false, true,  true,  true, false, false,  false,  false, false,  false, false, false,  false, false,true,true,true,true,true],
      [false, true, true,  true,  false, false, false,  false,  false, false,  false, false, false,  false, false,true,true,true,true,true],
      [false, true, true,  true,  false, false, false,  false,  false, false,  false, false, false,  false, true,true,true,true,true,true],
    ],
    "srcImg": "assets/puzzle-hard-3.webp"
  },
  {
    "id": 4,
    "name": "Корабль",
    "classColorText": "text-blue-600",
    "classBackground": "bg-blue-600",
    size: 20,
    sizeClasses: 'w-5 h-5 p-0 m-0 leading-4',
    textSizeClass: 'text-sm leading-3',
    "rowHints": [
      [0,0,0,0,3],
      [0,0,0,0,3],
      [0,0,0,0,1],
      [0,0,0,0,5],
      [0,0,0,5,3],
      [0,0,0,5,3],
      [0,0,5,1,1],
      [0,0,1,1,2],
      [0,0,8,1,3],
      [0,0,0,8,5],
      [0,0,0,8,5],
      [0,0,0,8,6],
      [0,0,0,8,7],
      [0,0,0,9,1],
      [0,0,0,1,6],
      [0,10,2,1,1],
      [0,0,0,0,16],
      [2,1,1,1,4],
      [0,0,0,0,12],
      [0,0,0,0,10],
    ],
    "colHints": [
      [0,0,0,0,1],
      [0,0,0,0,1],
      [0,0,0,3,1],
      [0,0,0,5,1],
      [0,0,0,6,2],
      [0,0,2,6,4],
      [0,2,4,6,5],
      [2,4,6,2,2],
      [0,0,0,0,20],
      [0,4,6,2,2],
      [1,1,2,1,4],
      [0,1,1,1,2],
      [0,0,2,1,4],
      [0,2,2,1,2],
      [0,0,0,0,16],
      [0,0,0,4,6],
      [0,0,5,1,3],
      [0,0,0,6,4],
      [0,0,7,1,1],
      [0,0,0,0,3],
    ],
    "solution": [
      [false, false, false,  false,  false, false, true,  true,  true, false,  false, false,  false,  false, false,false,false,false,false,false],
      [false, false, false,  false,  false, false, true,  true,  true, false,  false, false,  false,  false, false,false,false,false,false,false],
      [false, false, false,  false,  false, false, false,  false,  true, false,  false, false,  false,  false, false,false,false,false,false,false],
      [false, false, false,  false,  false, false, true,  true,  true, true,  true, false,  false,  false, false,false,false,false,false,false],
      [false, false, false,  false,  false, true, true,  true,  true, true,  false, false,  true,  true, true,false,false,false,false,false],

      [false, false, false,  false,  false, true, true,  true,  true, true,  false, false,  true,  true, true,false,false,false,false,false],
      [false, false, false,  false,  false, false, true,  true,  true, true,  true, false, false,  false, true,false,false,false,true,false],
      [false, false, false,  false,  false, false, false,  false,  true, false,  false, false, false,  false, true,false,false,true,true,false],
      [false, false, false,  false,  true, true, true,  true,  true, true,  true, true, false,  false, true,false,true,true,true,false],
      [false, false, false,  true,  true, true, true,  true,  true, true,  true, false, false,  false, true,true,true,true,true,false],

      [false, false, true,  true,  true, true, true,  true,  true, true,  false, false, false,  false, true,true,true,true,true,false],
      [false, false, true,  true,  true, true, true,  true,  true, true,  false, false, false,  true, true,true,true,true,true,false],
      [false, false, true,  true,  true, true, true,  true,  true, true, false, false, true,  true, true,true,true,true,true,false],
      [false, false, false,  true,  true, true, true,  true,  true, true,  true, true, false,  false, true,false,false,false,false,false],
      [false, false, false,  false,  false, false, false,  false,  true, false,  false, false, false,  false, true,true,true,true,true,true],

      [true, true, true,  true,  true, true, true,  true,  true, true,  false, false, false,  false, true,true,false,true,false,true],
      [false, false, false,  false,  true, true, true,  true,  true, true,  true, true, true,  true, true,true,true,true,true,true],
      [false, false, false,  false,  false, true, true,  false,  true, false,  true, false, true,  false, true,true,true,true,false,false],
      [false, false, false,  false,  false, true, true,  true,  true, true,  true, true, true,  true, true,true,true,false,false,false],
      [false, false, false,  false,  false, false, true,  true,  true, true,  true, true, true,  true, true,true,false,false,false,false],
    ],
    "srcImg": "assets/puzzle-hard-4.webp"
  },
];

export const PUZZLE = {
  EASY: puzzlesEasy,
  MEDIUM: puzzlesMedium,
  HARD: puzzlesHard
}
